/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Photo as PrismaPhoto,
  Event as PrismaEvent,
  User as PrismaUser,
} from "@prisma/client";
import { DeleteEventArgs } from "../../event/base/DeleteEventArgs";
import { Event } from "../../event/base/Event";
import { EventFindManyArgs } from "../../event/base/EventFindManyArgs";
import { EventCountArgs } from "../../event/base/EventCountArgs";

export class PhotoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PhotoCountArgs, "select">): Promise<number> {
    return this.prisma.photo.count(args);
  }

  async photos(args: Prisma.PhotoFindManyArgs): Promise<PrismaPhoto[]> {
    return this.prisma.photo.findMany(args);
  }
  async photo(args: Prisma.PhotoFindUniqueArgs): Promise<PrismaPhoto | null> {
    return this.prisma.photo.findUnique(args);
  }
  async createPhoto(args: Prisma.PhotoCreateArgs): Promise<PrismaPhoto> {
    return this.prisma.photo.create(args);
  }
  async updatePhoto(args: Prisma.PhotoUpdateArgs): Promise<PrismaPhoto> {
    return this.prisma.photo.update(args);
  }
  async deletePhoto(args: Prisma.PhotoDeleteArgs): Promise<PrismaPhoto> {
    return this.prisma.photo.delete(args);
  }

  async getEvent(parentId: string): Promise<PrismaEvent | null> {
    return this.prisma.photo
      .findUnique({
        where: { id: parentId },
      })
      .event();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.photo
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
  async DeletePhoto(args: DeleteEventArgs): Promise<Event> {
    throw new Error("Not implemented");
  }
  async GetEventPhotos(args: EventFindManyArgs): Promise<Event[]> {
    throw new Error("Not implemented");
  }
  async GetPresignedUrl(args: EventCountArgs): Promise<EventCountArgs> {
    throw new Error("Not implemented");
  }
}
